import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { WagmiProvider } from "@/lib/Providers";
import Navbar from "@/components/Navbar";

const roboto = Roboto({
  weight:[ "400", "700", "900","100","300","500",],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}   min-h-screen  mx-auto `}>
        <WagmiProvider>
          <Navbar/>
            {children}
        </WagmiProvider>
      </body>
    </html>
  );
}
